import type { Metadata } from "next";

import localFont from "next/font/local";
import { headers } from "next/headers";

import CowContextProvider from "@/context/CowContext";
import Web3Context from "@/context/Web3Context";

import Header from "@/components/Header";

import "@kleros/ui-components-library/style.css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = headers().get("cookie");

  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-klerosUIComponentsLightBackground antialiased`}
      >
        <Web3Context {...{ cookies }}>
          <Header />
          <CowContextProvider> {children} </CowContextProvider>
        </Web3Context>
      </body>
    </html>
  );
}
